import assert from "node:assert/strict";
import { generateKeyPairSync, sign as cryptoSign } from "node:crypto";
import test from "node:test";

import { EDDSA, ES256, RS256, parseCosePublicKey, verifyCoseSignature } from "./cose";

/**
 * These tests build COSE keys out of *real* key material generated by
 * `node:crypto`, sign real data with the matching private key, and check that
 * verification agrees.
 *
 * That is the only version of this test worth writing. Asserting that a
 * hand-written byte array parses into the fields you expect proves the parser
 * agrees with the person who wrote the byte array; making an actual signature
 * and verifying it proves the key that came out is the key that went in.
 */

// ---------------------------------------------------------------------------
// A minimal CBOR encoder, for tests only.
// ---------------------------------------------------------------------------
// The library decodes and never encodes, so there is nothing to reuse. Kept
// deliberately dumb: it handles exactly the shapes a COSE key needs.

function cborInt(value: number): number[] {
  if (value >= 0) {
    if (value < 24) return [value];
    if (value < 256) return [0x18, value];
    return [0x19, (value >> 8) & 0xff, value & 0xff];
  }
  const n = -1 - value;
  if (n < 24) return [0x20 | n];
  if (n < 256) return [0x38, n];
  return [0x39, (n >> 8) & 0xff, n & 0xff];
}

function cborBytes(bytes: Uint8Array): number[] {
  const length = bytes.length;
  const header =
    length < 24
      ? [0x40 | length]
      : length < 256
        ? [0x58, length]
        : [0x59, (length >> 8) & 0xff, length & 0xff];
  return [...header, ...bytes];
}

function coseKey(entries: [number, number | Uint8Array][]): Uint8Array {
  assert.ok(entries.length < 24, "the test encoder only does small maps");
  const out: number[] = [0xa0 | entries.length];
  for (const [key, value] of entries) {
    out.push(...cborInt(key));
    out.push(...(typeof value === "number" ? cborInt(value) : cborBytes(value)));
  }
  return Uint8Array.from(out);
}

const fromB64Url = (s: string) => Uint8Array.from(Buffer.from(s, "base64url"));

// ---------------------------------------------------------------------------

test("an ES256 key round-trips and verifies a real signature", () => {
  const { publicKey, privateKey } = generateKeyPairSync("ec", { namedCurve: "P-256" });
  const jwk = publicKey.export({ format: "jwk" });

  const cose = coseKey([
    [1, 2], // kty: EC2
    [3, ES256],
    [-1, 1], // crv: P-256
    [-2, fromB64Url(jwk.x as string)],
    [-3, fromB64Url(jwk.y as string)],
  ]);

  const parsed = parseCosePublicKey(cose);
  assert.equal(parsed.algorithm, ES256);

  const data = Buffer.from("authenticator data and a client data hash");
  const signature = cryptoSign("sha256", data, { key: privateKey, dsaEncoding: "der" });

  assert.equal(verifyCoseSignature(parsed, data, signature), true);
});

test("an ES256 signature over different data does not verify", () => {
  const { publicKey, privateKey } = generateKeyPairSync("ec", { namedCurve: "P-256" });
  const jwk = publicKey.export({ format: "jwk" });
  const parsed = parseCosePublicKey(
    coseKey([
      [1, 2],
      [3, ES256],
      [-1, 1],
      [-2, fromB64Url(jwk.x as string)],
      [-3, fromB64Url(jwk.y as string)],
    ]),
  );

  const signature = cryptoSign("sha256", Buffer.from("the real message"), {
    key: privateKey,
    dsaEncoding: "der",
  });

  assert.equal(
    verifyCoseSignature(parsed, Buffer.from("a different message"), signature),
    false,
  );
});

test("a corrupted signature is refused rather than throwing", () => {
  const { publicKey, privateKey } = generateKeyPairSync("ec", { namedCurve: "P-256" });
  const jwk = publicKey.export({ format: "jwk" });
  const parsed = parseCosePublicKey(
    coseKey([
      [1, 2],
      [3, ES256],
      [-1, 1],
      [-2, fromB64Url(jwk.x as string)],
      [-3, fromB64Url(jwk.y as string)],
    ]),
  );

  const data = Buffer.from("a message");
  const signature = cryptoSign("sha256", data, { key: privateKey, dsaEncoding: "der" });

  signature[5] ^= 0xff;
  assert.equal(verifyCoseSignature(parsed, data, signature), false);
  assert.equal(verifyCoseSignature(parsed, data, new Uint8Array(0)), false);
  assert.equal(verifyCoseSignature(parsed, data, Uint8Array.from([1, 2, 3])), false);
});

test("an RS256 key round-trips and verifies a real signature", () => {
  const { publicKey, privateKey } = generateKeyPairSync("rsa", { modulusLength: 2048 });
  const jwk = publicKey.export({ format: "jwk" });

  const parsed = parseCosePublicKey(
    coseKey([
      [1, 3], // kty: RSA
      [3, RS256],
      [-1, fromB64Url(jwk.n as string)],
      [-2, fromB64Url(jwk.e as string)],
    ]),
  );
  assert.equal(parsed.algorithm, RS256);

  const data = Buffer.from("authenticator data and a client data hash");
  const signature = cryptoSign("sha256", data, privateKey);
  assert.equal(verifyCoseSignature(parsed, data, signature), true);
  assert.equal(verifyCoseSignature(parsed, Buffer.from("other"), signature), false);
});

test("an Ed25519 key round-trips and verifies a real signature", () => {
  const { publicKey, privateKey } = generateKeyPairSync("ed25519");
  const jwk = publicKey.export({ format: "jwk" });

  const parsed = parseCosePublicKey(
    coseKey([
      [1, 1], // kty: OKP
      [3, EDDSA],
      [-1, 6], // crv: Ed25519
      [-2, fromB64Url(jwk.x as string)],
    ]),
  );
  assert.equal(parsed.algorithm, EDDSA);

  const data = Buffer.from("authenticator data and a client data hash");
  // Ed25519 hashes internally, so the digest argument is null.
  const signature = cryptoSign(null, data, privateKey);
  assert.equal(verifyCoseSignature(parsed, data, signature), true);
  assert.equal(verifyCoseSignature(parsed, Buffer.from("other"), signature), false);
});

test("a key whose type and algorithm disagree is refused", () => {
  // The algorithm-confusion guard. An EC2 key that declares RS256 must not be
  // accepted and then verified as something else.
  const { publicKey } = generateKeyPairSync("ec", { namedCurve: "P-256" });
  const jwk = publicKey.export({ format: "jwk" });

  assert.throws(
    () =>
      parseCosePublicKey(
        coseKey([
          [1, 2], // EC2
          [3, RS256], // ...claiming RSA
          [-1, 1],
          [-2, fromB64Url(jwk.x as string)],
          [-3, fromB64Url(jwk.y as string)],
        ]),
      ),
    /expected ES256/,
  );
});

test("algorithms outside the allowlist are refused", () => {
  const { publicKey } = generateKeyPairSync("ec", { namedCurve: "P-256" });
  const jwk = publicKey.export({ format: "jwk" });

  for (const algorithm of [-35, -36, -37, -47, 0, 1]) {
    assert.throws(
      () =>
        parseCosePublicKey(
          coseKey([
            [1, 2],
            [3, algorithm],
            [-1, 1],
            [-2, fromB64Url(jwk.x as string)],
            [-3, fromB64Url(jwk.y as string)],
          ]),
        ),
      /unsupported algorithm/,
      `should refuse algorithm ${algorithm}`,
    );
  }
});

test("an RSA key below 2048 bits is refused", () => {
  // Accepting a short modulus lets an authenticator choose to be forgeable.
  const { publicKey } = generateKeyPairSync("rsa", { modulusLength: 1024 });
  const jwk = publicKey.export({ format: "jwk" });

  assert.throws(
    () =>
      parseCosePublicKey(
        coseKey([
          [1, 3],
          [3, RS256],
          [-1, fromB64Url(jwk.n as string)],
          [-2, fromB64Url(jwk.e as string)],
        ]),
      ),
    /1024 bits/,
  );
});

test("P-256 coordinates of the wrong length are refused", () => {
  // Some parsers would treat a short value as left-padded, which is a different
  // point on the curve.
  assert.throws(
    () =>
      parseCosePublicKey(
        coseKey([
          [1, 2],
          [3, ES256],
          [-1, 1],
          [-2, new Uint8Array(31).fill(1)],
          [-3, new Uint8Array(32).fill(2)],
        ]),
      ),
    /must be 32 bytes/,
  );
});

test("unsupported curves and key types are refused", () => {
  assert.throws(
    () =>
      parseCosePublicKey(
        coseKey([
          [1, 2],
          [3, ES256],
          [-1, 2], // P-384
          [-2, new Uint8Array(32)],
          [-3, new Uint8Array(32)],
        ]),
      ),
    /unsupported curve/,
  );

  assert.throws(
    () => parseCosePublicKey(coseKey([[1, 9], [3, ES256]])),
    /unsupported key type/,
  );
});

test("a key missing its required fields is refused, not defaulted", () => {
  assert.throws(() => parseCosePublicKey(coseKey([[1, 2]])), /algorithm/);
  assert.throws(() => parseCosePublicKey(coseKey([[3, ES256]])), /key type/);
  assert.throws(
    () => parseCosePublicKey(coseKey([[1, 2], [3, ES256], [-1, 1], [-2, new Uint8Array(32)]])),
    /y coordinate/,
  );
});

test("garbage that is not CBOR at all is refused", () => {
  assert.throws(() => parseCosePublicKey(Uint8Array.from([0xff, 0xff, 0xff])));
  assert.throws(() => parseCosePublicKey(new Uint8Array(0)));
});
