import { BASE_MOVES, CORNER_COUNT, EDGE_COUNT, FACES, compose, type CubieCube } from "./cube";

/**
 * Looking at the same cube from other directions.
 *
 * Two-phase search is lopsided. Phase one drives the cube into the subgroup
 * generated by U, D and half turns of the rest — a subgroup defined by one axis,
 * U-D. A cube can be awkward from that axis and easy from another, and nothing in
 * the search can see that: it only ever looks one way.
 *
 * So the cube is also searched turned a third of the way round its URF-DBL
 * diagonal (which carries U to R to F), turned two thirds, and each of those
 * three inverted — six problems with the same answer length, one of which is
 * usually much easier than the rest. A solution to any of them converts back to
 * a solution of the original: rotate the moves back, and for an inverse, reverse
 * and invert them.
 *
 * ## The rotation, and why it is not trusted
 *
 * `URF3` is the 120° turn about the URF-DBL diagonal in Kociemba's cubie
 * numbering. It is written out once below; everything else here is DERIVED from
 * it — which face each face becomes is found by conjugating the six face turns
 * and asking which turn comes out, not typed in. `symmetry.test.ts` checks that
 * three of these turns are no turn at all and that the derived maps are
 * permutations of the faces, so a wrong entry in `URF3` cannot survive quietly.
 */
export const URF3: CubieCube = {
  cp: Uint8Array.from([0, 4, 5, 1, 3, 7, 6, 2]),
  co: Uint8Array.from([1, 2, 1, 2, 2, 1, 2, 1]),
  ep: Uint8Array.from([1, 8, 5, 9, 3, 11, 7, 10, 0, 4, 6, 2]),
  eo: Uint8Array.from([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
};

const URF3_INV = compose(URF3, URF3);

/** `k` quarter-thirds of rotation applied by conjugation: S^k C S^-k. */
export function rotate(cube: CubieCube, k: 0 | 1 | 2): CubieCube {
  let out = cube;
  for (let i = 0; i < k; i++) out = compose(compose(URF3, out), URF3_INV);
  return out;
}

/** The state that undoes `cube`: applying it after `cube` gives solved. */
export function inverse(cube: CubieCube): CubieCube {
  const out: CubieCube = {
    cp: new Uint8Array(CORNER_COUNT),
    co: new Uint8Array(CORNER_COUNT),
    ep: new Uint8Array(EDGE_COUNT),
    eo: new Uint8Array(EDGE_COUNT),
  };
  for (let i = 0; i < CORNER_COUNT; i++) {
    out.cp[cube.cp[i]] = i;
    out.co[cube.cp[i]] = (3 - cube.co[i]) % 3;
  }
  for (let i = 0; i < EDGE_COUNT; i++) {
    out.ep[cube.ep[i]] = i;
    out.eo[cube.ep[i]] = cube.eo[i];
  }
  return out;
}

function sameState(a: CubieCube, b: CubieCube): boolean {
  for (let i = 0; i < CORNER_COUNT; i++) {
    if (a.cp[i] !== b.cp[i] || a.co[i] !== b.co[i]) return false;
  }
  for (let i = 0; i < EDGE_COUNT; i++) {
    if (a.ep[i] !== b.ep[i] || a.eo[i] !== b.eo[i]) return false;
  }
  return true;
}

/**
 * For a cube rotated `k` times, the face (as an index into FACES) that each face
 * of its solution corresponds to on the original cube.
 *
 * A solution M1..Mn of S^k C S^-k is a solution of C once each move is replaced
 * by S^-k M S^k — which, for a rotation, is always another face turned the same
 * amount. Found by computing exactly that for each face and matching it against
 * the six face turns.
 */
function faceMapBack(k: 0 | 1 | 2): number[] {
  return FACES.map((face) => {
    let conjugated = BASE_MOVES[face];
    for (let i = 0; i < k; i++) conjugated = compose(compose(URF3_INV, conjugated), URF3);
    const match = FACES.findIndex((g) => sameState(conjugated, BASE_MOVES[g]));
    if (match < 0) throw new Error(`URF3 does not carry ${face} to a face turn`);
    return match;
  });
}

export const FACE_MAP_BACK: readonly (readonly number[])[] = [
  faceMapBack(0),
  faceMapBack(1),
  faceMapBack(2),
];

/** One way of looking at the cube, and how to translate its answer back. */
export interface Direction {
  cube: CubieCube;
  rotation: 0 | 1 | 2;
  inverted: boolean;
  /** Move indices solving `cube` → move indices solving the original. */
  toOriginal(moves: readonly number[]): number[];
}

/**
 * Moves are indexed face * 3 + (quarter turns - 1), faces in FACES order —
 * the layout `tables.ts` builds MOVES in.
 */
function mapMove(move: number, map: readonly number[]): number {
  return map[(move / 3) | 0] * 3 + (move % 3);
}

/** The same face, turned the other way: a quarter becomes its inverse, a half stays. */
function invertMove(move: number): number {
  const face = (move / 3) | 0;
  return face * 3 + (2 - (move % 3));
}

export function directionsOf(cube: CubieCube, count: 1 | 6): Direction[] {
  const out: Direction[] = [];
  const views: CubieCube[] = [cube, inverse(cube)];
  for (const rotation of [0, 1, 2] as const) {
    for (const inverted of [false, true]) {
      if (count === 1 && (rotation !== 0 || inverted)) continue;
      const map = FACE_MAP_BACK[rotation];
      out.push({
        cube: rotate(views[inverted ? 1 : 0], rotation),
        rotation,
        inverted,
        toOriginal(moves) {
          const rotated = moves.map((m) => mapMove(m, map));
          return inverted ? rotated.reverse().map(invertMove) : rotated;
        },
      });
    }
  }
  return out;
}
