import "server-only";

import type { RatingPool } from "../rating";
import type { Timed } from "../stats";
import type { Penalty } from "../types";
import { ATTEMPT_TTL_MS, type SubmittedMove } from "../verifySolve";
import { WEEKLY_ATTEMPTS, rankWeekly, weekEnd, weekKey, type Placed } from "../weekly";
import { db } from "./supabase";
import { verifyAndStore } from "./verifiedSolve";

/**
 * The weekly competition's server half. The rules, and why each exists, are in
 * `supabase/migrations/0017_weekly.sql`; this file keeps them.
 */

async function freshScramble(event: string): Promise<string> {
  const { randomScrambleForEvent } = await import("cubing/scramble");
  return (await randomScrambleForEvent(event)).toString();
}

/**
 * This week's five, generated by whichever request arrives first. Two
 * arriving together both generate, one insert wins on the key, and both then
 * read the winner's — so everybody gets the same five however the race goes.
 */
export async function ensureRound(week: string): Promise<{ week: string; event: string; scrambles: string[] }> {
  const existing = await db().from("weekly_rounds").select("week, event, scrambles").eq("week", week).maybeSingle();
  if (existing.data) return existing.data;

  const scrambles: string[] = [];
  for (let i = 0; i < WEEKLY_ATTEMPTS; i++) scrambles.push(await freshScramble("333"));
  await db().from("weekly_rounds").upsert({ week, event: "333", scrambles }, { onConflict: "week", ignoreDuplicates: true });

  const { data, error } = await db().from("weekly_rounds").select("week, event, scrambles").eq("week", week).single();
  if (error || !data) throw new Error(`Could not open this week's round: ${error?.message ?? "no row"}`);
  return data;
}

export interface WeeklyResult {
  idx: number;
  durationMs: number;
  penalty: Penalty;
  solveId: string | null;
}

export interface WeeklyStanding {
  week: string;
  /** Finished attempts, in order. */
  results: WeeklyResult[];
  /** An attempt opened and not yet finished — it becomes a DNF if abandoned. */
  open: { attemptId: string; idx: number; scramble: string; expiresAt: string } | null;
}

export async function standing(profileId: string, week: string, pool: RatingPool): Promise<WeeklyStanding> {
  const { data, error } = await db()
    .from("weekly_attempts")
    .select("id, idx, status, duration_ms, penalty, solve_id, expires_at")
    .eq("week", week)
    .eq("profile_id", profileId)
    .eq("pool", pool)
    .order("idx", { ascending: true });
  if (error) throw new Error(`Could not load your weekly: ${error.message}`);

  const results: WeeklyResult[] = [];
  let open: WeeklyStanding["open"] = null;
  for (const row of data ?? []) {
    if (row.status === "issued" && Date.parse(row.expires_at) > Date.now()) {
      const round = await ensureRound(week);
      open = { attemptId: row.id, idx: row.idx, scramble: round.scrambles[row.idx], expiresAt: row.expires_at };
    } else {
      // An attempt left open past its time is a DNF, whether or not anything
      // has closed it yet.
      const abandoned = row.status !== "completed";
      results.push({
        idx: row.idx,
        durationMs: abandoned ? 0 : (row.duration_ms ?? 0),
        penalty: abandoned ? "DNF" : ((row.penalty ?? "DNF") as Penalty),
        solveId: row.solve_id,
      });
    }
  }
  return { week, results, open };
}

export type IssueResult =
  | { ok: true; attemptId: string; idx: number; scramble: string; expiresAt: string }
  | { ok: false; status: number; error: string };

/**
 * Opens the next of your five. Any attempt you left open is closed as a DNF
 * first — the reroll defence, as in ranked: without it, a solve going badly
 * could be walked away from and the scramble "never happened".
 */
export async function issueWeeklyAttempt(profileId: string, pool: RatingPool, now = Date.now()): Promise<IssueResult> {
  const week = weekKey(now);
  const round = await ensureRound(week);

  const closed = await db()
    .from("weekly_attempts")
    .update({ status: "expired", penalty: "DNF", duration_ms: 0, completed_at: new Date(now).toISOString() })
    .eq("week", week)
    .eq("profile_id", profileId)
    .eq("pool", pool)
    .eq("status", "issued");
  if (closed.error) throw new Error(`Could not close the open attempt: ${closed.error.message}`);

  const { count, error: countError } = await db()
    .from("weekly_attempts")
    .select("id", { count: "exact", head: true })
    .eq("week", week)
    .eq("profile_id", profileId)
    .eq("pool", pool);
  if (countError || count === null) throw new Error("Could not count your attempts.");
  if (count >= WEEKLY_ATTEMPTS) {
    return { ok: false, status: 409, error: "You have done all five this week. The next round opens on Monday." };
  }

  // Never past the week's close: an attempt opened at 23:59 on Sunday belongs
  // to the week it was opened in, and must be finished inside it.
  const expiresAt = new Date(Math.min(now + ATTEMPT_TTL_MS, weekEnd(week))).toISOString();
  const { data, error } = await db()
    .from("weekly_attempts")
    .insert({ week, profile_id: profileId, idx: count, pool, issued_at: new Date(now).toISOString(), expires_at: expiresAt })
    .select("id, idx, expires_at")
    .single();
  // The unique key refused a second tab asking for the same attempt at once.
  if (error?.code === "23505") return { ok: false, status: 409, error: "That attempt is already open in another tab." };
  if (error || !data) throw new Error(`Could not open the attempt: ${error?.message ?? "no row"}`);

  return { ok: true, attemptId: data.id, idx: data.idx, scramble: round.scrambles[data.idx], expiresAt: data.expires_at };
}

export interface WeeklySubmission {
  profileId: string;
  attemptId: string;
  clientId: string;
  moves: SubmittedMove[];
  durationMs: number;
  penalty: Penalty;
  source: "keyboard" | "smartcube";
}

export type WeeklySubmitResult =
  | { accepted: true; idx: number; durationMs: number; penalty: Penalty; inspectionReason: string; done: number }
  | { accepted: false; reason: string };

export async function submitWeeklyAttempt(raw: WeeklySubmission): Promise<WeeklySubmitResult> {
  const input = { ...raw, durationMs: Math.round(raw.durationMs) };
  const { data: attempt } = await db().from("weekly_attempts").select("*").eq("id", input.attemptId).maybeSingle();

  // Not yours is the same answer as not there.
  if (!attempt || attempt.profile_id !== input.profileId) return { accepted: false, reason: "No such attempt." };
  if (attempt.status !== "issued") return { accepted: false, reason: "That attempt is already finished." };

  const receivedAt = Date.now();
  const round = await ensureRound(attempt.week);

  const finish = async (solveId: string | null, durationMs: number, penalty: Penalty) => {
    const { error } = await db()
      .from("weekly_attempts")
      .update({ status: "completed", solve_id: solveId, duration_ms: durationMs, penalty, completed_at: new Date(receivedAt).toISOString() })
      .eq("id", attempt.id)
      // Two submissions racing cannot both write a result.
      .eq("status", "issued");
    if (error) throw new Error(`Could not record the result: ${error.message}`);
  };
  const done = async () => {
    const { count } = await db()
      .from("weekly_attempts")
      .select("id", { count: "exact", head: true })
      .eq("week", attempt.week)
      .eq("profile_id", attempt.profile_id)
      .eq("pool", attempt.pool)
      .neq("status", "issued");
    return count ?? 0;
  };

  if (input.penalty === "DNF") {
    await finish(null, input.durationMs, "DNF");
    return { accepted: true, idx: attempt.idx, durationMs: input.durationMs, penalty: "DNF", inspectionReason: "", done: await done() };
  }

  // An attempt's deadline is never past the week's close, which can be sooner
  // than the verifier's own thirty minutes: a solve arriving after it is a DNF
  // in the week it was opened, not a result carried into the next.
  if (receivedAt > Date.parse(attempt.expires_at)) {
    await finish(null, input.durationMs, "DNF");
    return { accepted: false, reason: "That attempt's time ran out before the solve arrived." };
  }

  const outcome = await verifyAndStore({
    profileId: attempt.profile_id,
    clientId: input.clientId,
    event: round.event,
    scramble: round.scrambles[attempt.idx],
    issuedAt: Date.parse(attempt.issued_at),
    receivedAt,
    moves: input.moves,
    durationMs: input.durationMs,
    penalty: input.penalty,
    source: input.source,
    mode: "weekly",
  });

  if (!outcome.verified) {
    await finish(null, input.durationMs, "DNF");
    return { accepted: false, reason: outcome.reason };
  }
  await finish(outcome.solveId, input.durationMs, outcome.penalty);
  return {
    accepted: true,
    idx: attempt.idx,
    durationMs: input.durationMs,
    penalty: outcome.penalty,
    inspectionReason: outcome.inspectionReason,
    done: await done(),
  };
}

export interface WeeklyBoard {
  week: string;
  placed: Placed[];
  /** Started and not yet finished all five. */
  competing: number;
}

/** Everybody's five for a week, ranked. */
export async function weeklyBoard(week: string, pool: RatingPool = "keyboard"): Promise<WeeklyBoard> {
  const rows: { profile_id: string; idx: number; status: string; duration_ms: number | null; penalty: string | null; expires_at: string }[] = [];
  for (let from = 0; ; from += 1000) {
    const { data, error } = await db()
      .from("weekly_attempts")
      .select("profile_id, idx, status, duration_ms, penalty, expires_at")
      .eq("week", week)
      .eq("pool", pool)
      .order("profile_id")
      .order("idx")
      .range(from, from + 999);
    if (error) throw new Error(`Could not load the weekly board: ${error.message}`);
    rows.push(...(data ?? []));
    if (!data || data.length < 1000) break;
  }

  const byProfile = new Map<string, Timed[]>();
  const now = Date.now();
  for (const row of rows) {
    const live = row.status === "issued" && Date.parse(row.expires_at) > now;
    if (live) continue;
    const list = byProfile.get(row.profile_id) ?? [];
    list.push(
      row.status === "completed"
        ? { ms: row.duration_ms ?? 0, penalty: (row.penalty ?? "DNF") as Penalty }
        : { ms: 0, penalty: "DNF" },
    );
    byProfile.set(row.profile_id, list);
  }

  const ids = [...byProfile.keys()];
  const names = new Map<string, { handle: string; display_name: string }>();
  for (let i = 0; i < ids.length; i += 200) {
    const { data } = await db().from("profiles").select("id, handle, display_name").in("id", ids.slice(i, i + 200));
    for (const p of data ?? []) names.set(p.id, p);
  }

  const competitors = ids
    .filter((id) => names.has(id))
    .map((id) => ({ handle: names.get(id)!.handle, displayName: names.get(id)!.display_name, results: byProfile.get(id)! }));
  const placed = rankWeekly(competitors);
  return { week, placed, competing: competitors.length - placed.length };
}

/** A week's five, but only once it has closed. */
export async function closedScrambles(week: string, now = Date.now()): Promise<string[] | null> {
  if (now < weekEnd(week)) return null;
  const { data } = await db().from("weekly_rounds").select("scrambles").eq("week", week).maybeSingle();
  return data?.scrambles ?? null;
}

/** Weeks that ran, newest first. */
export async function pastWeeks(before: string, limit = 12): Promise<string[]> {
  const { data } = await db().from("weekly_rounds").select("week").lt("week", before).order("week", { ascending: false }).limit(limit);
  return (data ?? []).map((r) => r.week);
}
